---

- hosts: digitalocean-local

  vars:
    do_token: "{{ lookup('env', 'DO_API_TOKEN') }}"

  tasks:
    - name: ensure demo droplet(s) are cleaned up
      digital_ocean: >
        state=absent
        command=droplet
        name={{ item }}
        size_id=512mb
        region_id=nyc3
        image_id=ubuntu-16-04-x64
        api_token={{ do_token }}
        unique_name=yes
      with_sequence: start=1 end={{ web_instances }} format=demo-web-%02x
