---

- hosts: digitalocean-local

  vars:
    do_token: "{{ lookup('env', 'DO_API_TOKEN') }}"

  tasks:
    - name: ensure ssh key exists
      user: >
        name={{ ansible_user_id }}
        generate_ssh_key=yes
        ssh_key_file=.ssh/id_rsa

    - name: ensure key exists at DigitalOcean
      digital_ocean: >
        state=present
        command=ssh
        name=MacBook
        ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
        api_token={{ do_token }}
      register: my_ssh_key

    - name: ensure demo droplet exists
      digital_ocean: >
        state=present
        command=droplet
        name=demo-droplet
        size_id=512mb
        region_id=nyc3
        image_id=ubuntu-14-04-x64
        ssh_key_ids={{ my_ssh_key.ssh_key.id }}
        api_token={{ do_token }}
        unique_name=yes
      register: demo_droplet

    - name: droplet info
      debug: msg="{{ demo_droplet.droplet.name }} ({{ demo_droplet.droplet.id }}) IP is {{ demo_droplet.droplet.ip_address }}"

    - name: make sure our tag for this demo exists
      digital_ocean_tag:
        name: ansible-demo
        state: present
        resource_id: "{{ demo_droplet.droplet.id }}"
